### PR TITLE
Verus Float Speed Fix!

### PR DESCRIPTION
**Pull request by RtxOP**
ong fr fr

### CODE REVIEW

**Comment by Davidisnotavailable** [comment]
insane if it works?!?"!§?!"

**Comment by NCPUser** [comment]
Its so good

**Comment by RtxOP** [comment]
OH SHIT i didn't know it commited to here

**Comment by NCPUser** [comment]
> OH SHIT i didn't know it commited to here

ok

**Comment by NCPUser** [comment]
Bro made grimdamage fly better ye

**Comment by RtxOP** [comment]
it was supposed to go to my dev branch I fixed it now. stop whining like a baby

**Comment by NCPUser** [comment]
> it was supposed to go to my dev branch I fixed it now. stop whining like a baby

bulid failed

**Comment by RtxOP** [comment]
check again

**Comment by Davidisnotavailable** [comment]
> check again

forgot to import :rofl:

**Comment by RtxOP** [comment]
so funni

**Comment by RtxOP** [comment]
close this pull req you already merged all the stuff in the other one zywl

**Pull request closed without merging**
