### PR TITLE
SmoothCamera feature

### PR DESCRIPTION
**Pull request by dizwi**

### CODE REVIEW

**Comment by qazwsx-11** [comment]
Useless feature

**Comment by dizwi** [comment]
> Useless feature

no

**Comment by n1ckyl337** [comment]
yes

**Comment by walababa** [comment]
No

**Comment by gabrielvicenteYT** [comment]
I gave Zywl that code first, btw big rise skid

**Comment by gatooooooo** [comment]
# **am i first?**
i think i am.

**Pull request merged**
