### PR TITLE
Update MinemoraGlide.kt

### PR DESCRIPTION
**Pull request by Zerolysimin**
i write the code in github...   hopefully it work

### CODE REVIEW

**Comment by MatrixU5er** [comment]
I think 。。
0W )EMR`7Z6NU`T) TK{SY2

**Comment by Zerolysimin** [comment]
oh F. rip

**Comment by Zerolysimin** [comment]
didnt notice it. coz i write it in github and not in intelij / eclipse

**Comment by Zerolysimin** [comment]
just change this "Glide4" To "Glide3"

image

**Comment by C00LC0D35** [comment]
no

**Pull request closed without merging**
