### PR TITLE
AAC5 Crtiticals

### PR DESCRIPTION
**Pull request by NCPUser**
Bypass AAC5 Anticheat

### CODE REVIEW

**Comment by RtxOP** [comment]
this guy is a skidding machine

**Comment by Davidisnotavailable** [comment]
when fix grim fly

**Comment by RtxOP** [comment]
> > when fix grim fly
> 
> tnt used?

It only works with explosions now lmfao

**Comment by NCPUser** [comment]
> > > when fix grim fly
> > 
> > 
> > tnt used?
> 
> It only works with explosions now lmfao

yea

**Comment by NCPUser** [comment]
closed new pull check

**Pull request closed without merging**
