### PR TITLE
Add "KeepTools" option in InvManager

### PR DESCRIPTION
**Pull request by StupidQu**
Add "KeepTools" option in InvManager

### CODE REVIEW

**Comment by FDPUser443** [comment]
I'm not sure it works correctly; What is "KeepTools" option supposed to do? Is it nessecary to log while selecting an item? [ ClientUtils.logInfo("Compare $slot with $sslot") ] https://youtu.be/2OOwnSEAJhQ

**Comment by StupidQu** [comment]
> I'm not sure it works correctly; What is "KeepTools" option supposed to do? Is it nessecary to log while selecting an item? [ ClientUtils.logInfo("Compare $slot with $sslot") ] https://youtu.be/2OOwnSEAJhQ

Sorry, I used it to debug, but i forgot to delete it. This option supposed to keep the best tool in the inventory, and it has some bugs. I'm fixing it.

**Comment by StupidQu** [comment]
It works well now.

**Comment by FDPUser443** [comment]
It doesn't consider tool enchantments; [https://youtu.be/gtiklsuaxOs]

**Comment by StupidQu** [comment]
sorry, I didn't consider enchantments, I will fix it soon



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月15日(星期六) 凌晨0:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SkidderMC/FDPClient] Add &quot;KeepTools&quot; option in InvManager (PR #806)





 
It doesn't consider tool enchantments; [https://youtu.be/gtiklsuaxOs]

**Comment by StupidQu** [comment]
Now it will consider enchantments

**Comment by FDPUser443** [comment]
It can be a bit better: https://github.com/StupidQu/FDPClient/pull/1
Check it out pls;

**Comment by StupidQu** [comment]
> It can be a bit better: [StupidQu#1](https://github.com/StupidQu/FDPClient/pull/1) Check it out pls;

You are right, I am not very familiar with Mod development, thank you.

**Pull request merged**
